[package]
name = "batl-macros"
version = "0.2.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.83"
quote = "1.0.36"
semver = "1.0.23"
syn = { version = "2.0.65", features = ["full"] }
