[environment]
version = "0.3.0"

[repository]
name = "battalion.batl"
version = "0.1.0"

[scripts]
install = "cargo install --debug --path packages/batl"

[dependencies]
"battalion.source.github" = "0.1.0"
"battalion.source.tar" = "0.1.0"

[links]
"battalion.source.tar@0.1.0" = "core/source/tar"
"battalion.source.github@0.1.0" = "core/source/github"

[restrict.Unix]
include = "require"

[[sources]]
handler = "battalion.source.git"
url = "https://github.com/frqubit/batl"
